#Number Guessing game
#INFO 101 Project 
#Author - Arham Choraria 
#Version 1.0

#Importing random in order to generate random numbers
import random

print("Welcome! Let's get to know the rules first: ")
print("You will have to guess a number between 0 and 100 and match it with the value generated by the computer ")
print("You can choose the number of guesses you want in order to make the game difficult/easy ")
print("----------------------------------------------------------------")
print("Let's play!")

# A method where the main game is played and the user's guesses are checked
def game():
  #Boolean variable checking whether the guess is correct or not
  correct = False;
  #Declaring an integer and generating a random number between 0 and 100
  number = random.randint(0,100)
  #Declaring a list to store all the guesses made by the user
  listOfGuesses = []
  #Integer variable keeping the number of guesses the user wants
  guessNo = int(input("Please enter the number of guesses you want "))
  #Checking whether the value is acceptable or not
  if (guessNo <= 0):
    print("You have entered an invalid number. Please enter a positive integer")
    guessNo = int(input())

  print("Let's see what you've got! Guess a number between 0 and 100")

  # A loop that iterates the number of times guessNo has been stored with
  for x in range(guessNo):
    #Integer variable storing the value being guessed by the user
    userGuess = int(input())
    #Checking whether the value entered is acceptable or not
    if (userGuess > 100 or userGuess < 0) :
      print("You have entered an invalid number. Please enter a number between 0 and 100 only")
      userGuess = int(input())
    #Adding the guessed value to the list
    listOfGuesses.append(userGuess)
    #Checking if the user has guessed right
    if userGuess == number:
      print("Great job! You guessed it right! You've won!")
      print("Here are your guessed numbers: ")
      print(listOfGuesses)
      correct = True
      break
    #Checking if the user has guessed low
    elif userGuess < number:
      print("Raise the bar! You are guessing a little low!")
    #Checking if the user has guessed high
    elif userGuess > number:
      print("Come back down! You are guessing too high!")
  #Checking if the user's no. of guesses are over and if the user has lost
  if correct == False:
    print("Oops! You've crossed the number of guesses. Better luck next time!")
    print("The number is " + str(number) + ".")
  #Calling the function playAgain if the user wants to play more
  playAgain()

# A function to check if the user wants to play again
def playAgain(): 
  print("Want to give it another try? Enter 'yes' to play again! Enter anything else to end the game.")
  num = str(input())
  if num == 'yes': 
    print("Let's play again!")
    game()
  else:
    print("It was a good game! Thank you for playing. Hope to see you soon!")

if __name__ == "__main__":
    game()
